name: Deploy to ECS

on:
  push:
    branches: [main]

env:
  BEFORE_SHA: ${{ github.event.before }}
  REGION: "eu-west-1"
  ECS_CLUSTER: "dev-fplarache-smartlib-user-cluster"
  ECS_SERVICE: "dev-smartlib-user-service"
  TASK_DEFINITION: "dev-smartlib-user-td"
  IMAGE_URI: "dev-fplarache-smartlib-user-repository:latest"

jobs:
  setup:
    name: "Deploy to ECS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Maven
        uses: actions/setup-java@v3
        with:
          maven-version: "3.8.4"

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build with Maven
        run: mvn clean install

      - name: Publish Docker image
        id: publish-image
        run: |
          docker build -t ${{ env.IMAGE_URI }} .
          docker push ${{ env.IMAGE_URI }}

      - name: Register ECS Task Definition
        run: |
          TASK_DEFINITION_JSON=$(jq -n --arg IMAGE_URI "${{ env.IMAGE_URI }}" \
            '{
              family: "dev-smartlib-user-td",
              networkMode: "awsvpc",
              containerDefinitions: [
                {
                  name: "dev-smartlib-user-container",
                  image: $IMAGE_URI,
                  memory: 512,
                  cpu: 256,
                  essential: true,
                  logConfiguration: {
                    logDriver: "awslogs",
                    options: {
                      "awslogs-group": "/ecs/dev-smartlib-user",
                      "awslogs-region": $REGION,
                      "awslogs-stream-prefix": "ecs"
                    }
                  }
                }
              ],
              requiresCompatibilities: ["FARGATE"],
              cpu: "256",
              memory: "512",
              executionRoleArn: "arn:aws:iam::YOUR_ACCOUNT_ID:role/AmazonECS_FargateTaskExecutionRole"
            }')

          echo "$TASK_DEFINITION_JSON" > ecs/task-definition.json
          NEW_TASK_DEFINITION=$(aws ecs register-task-definition --cli-input-json file://ecs/task-definition.json --query "taskDefinition.taskDefinitionArn" --output text)
          echo "NEW_TASK_DEFINITION=$NEW_TASK_DEFINITION" >> $GITHUB_ENV

      - name: Deploy ECS Service
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
